### ISSUE TITLE
Number of targets collected increases every time a new rover is selected

### ISSUE THREAD

**Issue by AlpNov** [BCLab-UNM/Swarmathon-ROS#13]
Under the Task Status tab of the GUI, targets collected label seems to increase by a variable amount, targets detected and obstacle avoidance calls seems to be stable. Eventually targets collected could get larger than targets detected, and larger than 256.

Digging into the rover_gui_plugin.cpp file right now to see where this could come from.

**Comment by jhecker** [comment]
Thanks An, we're looking at this now and will apply a fix as soon as possible. Please keep us updated if you find the culprit...

**Comment by jhecker** [comment]
This bug has been squashed with hotfix-0.5.6: af97c27cb039ed8ca4ae1fb5ccb0366308e85ca5
