### ISSUE TITLE
The map seems to have an inappropriate width sometimes.

### ISSUE THREAD

**Issue by gmfricke** [BCLab-UNM/Swarmathon-ROS#16]
Empty space to the east of center.
<img width="556" alt="mapissue" src="https://cloud.githubusercontent.com/assets/3946771/12517696/634642a2-c0f1-11e5-8336-7d4c7b8152d7.png">

**Comment by Antonio-Griego** [comment]
map width changes to maintain aspect ratio; this is not technically a bug, but a future feature update may be implemented to improve map graphics

**Comment by gmfricke** [comment]
This was not actually a bug. The width seems to large in order to maintain aspect ratio.
