### ISSUE TITLE
Startup crash on new install

### ISSUE THREAD

**Issue by kstolleis** [BCLab-UNM/Swarmathon-ROS#17]
setting /run_id to 6d5a6af2-c1e6-11e5-8f4c-d85d4cf2e0b8
process[rosout-1]: started with pid [5235]
started core service [/rosout]
./run.sh: line 11:  5252 Segmentation fault      (core dumped) rqt -s rqt_rover_gui
Cleaning up ROS and Gazebo Processes
killing:
 * /rosout
 * /rqt_gui_cpp_node_5252

Reproduced multiple times with clean install and build

**Comment by jhecker** [comment]
Apparently resolved after a full reinstall of Ubuntu 14.04.

This may need to be reopened in the future pending any further issues, but closing for now...
