### ISSUE TITLE
'source ~/.bashrc' problems

### ISSUE THREAD

**Issue by abentleym** [BCLab-UNM/Swarmathon-ROS#18]
I'm trying to fully install and run the simulator on ROS, but during installation whenever I enter in **source ~/.bashrc** into the terminal, I receive a message:
**bash: export: `/home/alexander/.bashrc': not a valid identifier**

**Comment by jhecker** [comment]
It looks like you have the line ```export /home/alexander/.bashrc``` somewhere inside your **.bashrc** file. I'm not sure how that happened, but just to double-check, can you please run ```cat .bashrc | tail -5``` in your **Terminal** program, then copy and paste the output here?

**Comment by abentleym** [comment]
This is the output I got:
**source ~/rover_workspace/devel/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash**

**Comment by jhecker** [comment]
Ok, aside from have 3 duplicate lines sourcing the ROS setup file, this looks ok, except I don't see the ```export GAZEBO_MODEL_PATH``` line. Let's try ```cat .bashrc | tail -10```, please.

**Comment by abentleym** [comment]
Okay, now it gives me:
**fi
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source ~/rover_workspace/devel/setup.bash source /home/alexander/.bashrc
export GAZEBO_MODEL_PATH=~/rover_workspace/misc/models source /home/alexander/.bashrc
source ~/rover_workspace/devel/setup.bash
source /opt/ros/indigo/setup.bash**

**Comment by jhecker** [comment]
Ok, you have two ```source /home/alexander/.bashrc``` that should not be there.

Delete both of those, as well as the two duplicate ```source /opt/ros/indigo/setup.bash``` (not required, but let's clean up anyway), and try running the simulation.

**Comment by abentleym** [comment]
I think I might have done something wrong, because now when I try **source ~/.bashrc** I get:
**bash: /home/alexander/rover_workspace/devel/setup.bash: No such file or directory
bash: export: `/home/alexander/.bashrc': not a valid identifier
bash: /home/alexander/rover_workspace/devel/setup.bash: No such file or directory
bash: /home/alexander/rover_workspace/devel/setup.bash: No such file or directory**

**Comment by jhecker** [comment]
Yikes. Ok, please run ```cat ~/.bashrc | tail -10``` once more, and be sure to paste all 10 lines here. I'll do my best to correct them, then have you copy and paste the corrected lines back into your **.bashrc** file.

**Comment by jhecker** [comment]
Closing this issue for now -- please reopen if needed, otherwise, refer to the README for any further questions.

**Comment by abentleym** [comment]
My fault, I've been MIA for the past few days, but I'm still having problems. Here's the output from the command you gave me:

source /opt/ros/indigo/setup.bash
source ~/rover_workspace/devel/setup.bash source /home/alexander/.bashrc
export GAZEBO_MODEL_PATH=~/rover_workspace/misc/models source /home/alexander/.bashrc
source ~/rover_workspace/devel/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source ~/rover_workspace/devel/setup.bash
source /opt/ros/indigo/setup.bash

**Comment by gmfricke** [comment]
Hello and thanks for being part of the Swarmathon!

The first thing I notice is that this line is out of date:

export GAZEBO_MODEL_PATH=~/rover_workspace/misc/models source /home/alexander/.bashrc

From the errors you reported there may be other things going on too.

I think the simplest thing to do is backup your rover_workspace directory (unless you haven't made any changes to the source). Then delete that directory and follow the README instructions starting at Step 5: Install Swarmathon-ROS to reinstall.

Note any errors you encounter.

**Comment by abentleym** [comment]
Okay, I'll try that and let you know what happens. Thanks!

**Comment by abentleym** [comment]
Okay, from the first step **git clone**, the terminal tells me:
**fatal: destination path 'Swarmathon-ROS' already exists and is not an empty directory.*

**Comment by jhecker** [comment]
Matthew's point about the GAZEBO_MODEL_PATH being incorrect is a good one, but I don't think removing the rover_workspace directory will be of any help here -- your .bashrc is outside of this directory, and it needs to be modified before the code will compile correctly.

Unfortunately, I'll need to see more lines from your .bashrc before I can give you an official correction.

Please run ```cat ~/.bashrc | tail -20``` and paste the results here.

**Comment by abentleym** [comment]
Here is the output from the command:
**# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source ~/rover_workspace/devel/setup.bash source /home/alexander/.bashrc
export GAZEBO_MODEL_PATH=~/rover_workspace/misc/models source /home/alexander/.bashrc
source ~/rover_workspace/devel/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source /opt/ros/indigo/setup.bash
source ~/rover_workspace/devel/setup.bash
source /opt/ros/indigo/setup.bash**


I already removed the **rover_workspace** directory, should I just paste it back where it was befor

**Comment by jhecker** [comment]
Ok, let's open your **.bashrc** file with the command ```nano ~/.bashrc```, then use your keyboard or mouse to move the blinking cursor all the way to the end of the file.

Starting from the bottom, please delete everything up to and including the very first occurrence of ```source /opt/ros/indigo/setup.bash``` (after the last ```fi```), then save and exit the file using <kbd>Ctrl</kbd> + <kbd>x</kbd>.

Make sure to run ```source ~/.bashrc``` once more to refresh the settings (and to ensure everything's working as expected).

Assuming the line above works without printing any errors, make sure you ```rm ~/rover_workspace``` and ```rm ~/Swarmathon-ROS```, then resume the installation process at [Step 5](https://github.com/BCLab-UNM/Swarmathon-ROS#5-install-swarmathon-ros) as Matthew recommended.

Please be sure to follow the instructions ***exactly*** as written. I would recommend copying and pasting the commands directly into your **Terminal**.

**Comment by abentleym** [comment]
Okay, I followed all of your instructions, and I'm going to resume the installation process soon. I'll let you know if I encounter any more problems.

**Comment by abentleym** [comment]
I was able to successfully re-installed ROS without any errors or problems. I'll test the software more thoroughly tomorrow, and let you know if I have any problems.
Thanks for all your help!

**Comment by jhecker** [comment]
Excellent, I'm glad the install went well. I'll leave the issue open for now -- please update us when you can.

**Comment by mike-matera** [comment]
Hi All, 

Here's how to reset your .bashrc file if it's beyond repair:

```
cp ~/.bashrc ~/.bashrc.bak
cp /etc/skel/.bashrc ~/.bashrc
echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
echo "source ~/rover_workspace/devel/setup.bash" >> ~/.bashrc
echo "export GAZEBO_MODEL_PATH=~/rover_workspace/simulation/models" >> ~/.bashrc
echo "export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:~/rover_workspace/devel/lib/" >> ~/.bashrc
```

This will erase any of your own non Swarmathon customizations. If you have any customizations you probably also don't need these instructions. You should probably log out and back in after this.

**Comment by jhecker** [comment]
Excellent, thanks Mike

**Comment by arrfou99** [comment]
Thank you   jhecker ... works for me
