### ISSUE TITLE
Task Status at GUI

### ISSUE THREAD

**Issue by Dokonjo** [BCLab-UNM/Swarmathon-ROS#21]
The GUI is not reading the number of targets detected nor collected, but the obstacle detection works.

**Comment by jhecker** [comment]
Hello,

The target detection system in the GUI had been updated as per the official Swarmathon rules. In order to receive credit for your

**Comment by Dokonjo** [comment]
You mean to say that the GUI must show a picture of the target then a picture of the collection zone tag? Then how do you count the number of tags collected?

**Comment by jhecker** [comment]
Not quite -- please consult the competition rules under "Resources", there you'll see the specification for "Finding a resource" and what's required. Note that only one target is counted per trip.
