### ISSUE TITLE
April tag detection seems unreliable.

### ISSUE THREAD

**Issue by mike-matera** [BCLab-UNM/Swarmathon-ROS#22]
Hello, 

In my testing I've detected differences in the April tags seen in target.cpp and those seen in the simulation GUI for the same image. Would you please pull my branch:

Swarmathon-Cabrillo.git / targetimage-debug

I have instrumented the code to demonstrate the problem. You can launch the simulator with the command: 

./run.sh --startsim --single 

This launches with a single rover and makes it easier on the eyeballs. Once running the rover reports what it sees on the topic: 

/achilles/state_machine

Also, the GUI tells you what tags it sees in every picture it's sent. They are sometimes different. Which freaks me out a little.

**Comment by jhecker** [comment]
Resolved through pull request https://github.com/BCLab-UNM/Swarmathon-ROS/pull/24 (b9adfb42389475ab15c5e080a507473b22a6be6d): the target detection AprilTag library was obsolete and has now been replaced by the newest rqt GUI version.
