### ISSUE TITLE
rosnode obstacle is not running in simulation

### ISSUE THREAD

**Issue by jjakenichol** [BCLab-UNM/Swarmathon-ROS#27]
When in all autonomous mode, all robots quickly run into the walls and get stuck.  When running rosnode list in the terminal, obstacle node is not listed.

~/rover_workspace$ rosnode list
/achilles_EKF
/achilles_MOBILITY
/achilles_NAVSAT
/achilles_TARGET
/aeneas_EKF
/aeneas_MOBILITY
/aeneas_NAVSAT
/aeneas_TARGET
/ajax_EKF
/ajax_MOBILITY
/ajax_NAVSAT
/ajax_TARGET
/gazebo
/joy_node
/rosout
/rqt_gui_cpp_node_2398

**Comment by jhecker** [comment]
Jake,

I tested this on both my machine and yours (under my account), and surprisingly enough, I can't seem to replicate the issue -- the obstacle nodes start up exactly as expected.

I'm thinking something may have gone wrong during the compilation process, causing the obstacle package to not get compiled... I'll close the issue for now -- hopefully it's something specific related to that machine (including the time skew errors).
