### ISSUE TITLE
QPoint in the rover placement in sim should be QPointF

### ISSUE THREAD

**Issue by gmfricke** [BCLab-UNM/Swarmathon-ROS#35]
QPoint is integer precision so the rover x and y positions are restricted to integer meters when added to Gazebo. Replacing with QPointF fixes the problem.

**Comment by Antonio-Griego** [comment]
corrected the issue in [hotfix-1.1.10](https://github.com/BCLab-UNM/Swarmathon-ROS/commit/8df2a315e98fac18ff96f7a872c2f08088d6b692)
