### ISSUE TITLE
catkin_make fails: Missing NavSOL.h file

### ISSUE THREAD

**Issue by eduran0826** [BCLab-UNM/Swarmathon-ROS#48]
When following normal setup instructions on the README of the repository, an error is present at around 86% completion after running catkin_make. It states that the file NavSOL.h does not exist. 

![fullsizerender](https://cloud.githubusercontent.com/assets/12473592/22049973/92deb008-dcfc-11e6-86c7-3540e5563cb7.jpg)

**Comment by JCHJones** [comment]
please post problems in the software section of the Q&A forum until it is confirmed that you have found a bug. Go [here](http://nasaswarmathon.com/qa-forum/?p=post%3Fid%3D8367719) and you will see I have replied with a possible solution.
