### ISSUE TITLE
Add line for rqt  and cv-bridge and image_transport packages

### ISSUE THREAD

**Issue by eselkin** [BCLab-UNM/Swarmathon-ROS#5]
sudo apt-get install ros-indigo-rqt ros-indigo-cv-bridge ros-indigo-image-transport 

or else catkin_make fails

**Comment by mike-matera** [comment]
Hi, 
I didn't notice this problem. When you installed ROS did you do this? 

sudo apt-get install ros-indigo-dektop-full 

That installs ros-indigo-perception which depends on ros-indigo-vision-opencv, which pulls in ros-indigo-cv-bridge and possibly the others.

**Comment by eselkin** [comment]
I did do the ros-indigo-desktop-full, so I'm not sure why they weren't installed. The dependencies do seem to be there.

**Comment by jhecker** [comment]
Hello there -- thank you for your comment.

As with Mike, I haven't experienced any compilation issues when using the full install of ROS Indigo. I do know that ROS Indigo is not officially supported under Ubuntu 15.10 according to [REP 3](http://www.ros.org/reps/rep-0003.html), so I can't be sure of what issues might arise using that particular release.

Please reply to the thread once you've had time to test a clean install; I'll leave the Issue open in the mean time.

**Comment by eselkin** [comment]
It works well under 15.10, just with those packages installed separately. On 14.04 the packages install fine and catkin_make has no errors using just the ros-indigo-desktop-full. I'm using 15.10 only because the default kernel handles better while virtualized. Sorry to create an issue when there isn't one.

**Comment by jhecker** [comment]
Thanks for the update -- I'm excited to hear that 15.10 seems to be compatible once those small tweaks are made.

Although we're pushing the 14.04/Indigo configuration this year for simplicity, we're still very eager to hear from teams that are willing to try alternative setups. If you wouldn't mind, perhaps you could open a discussion thread on the [Q&A Forum](http://nasaswarmathon.com/qa-forum/) regarding forward compatibility.

I'll close this Issue for now.
