### ISSUE TITLE
Noticing a common issue with ublox submodule

### ISSUE THREAD

**Issue by eselkin** [BCLab-UNM/Swarmathon-ROS#50]
Many people seem to be building the latest versions with issues that navSOL.h (ublox_msgs: http://docs.ros.org/fuerte/api/ublox_msgs/html/NavSOL_8h_source.html) does not exist. Is this an incompatibility from an update to some library/component of ROS? I posted an issue to the ublox github repo as well to see if it stems from there.

**Comment by jhecker** [comment]
This issue is resolved by building the software with ```catkin build``` instead of ```catkin_make```. Check out the last few posts in our [Bug Reports thread](http://swarmathon.discussion.community/post/bug-reports-201617-competition-season-8367719) for more details.
